version: '3'

services:
  frontend:
    build:
      context: ./dashboardcovidapi
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build:
      context: ./covidapi
    ports:
      - "8080:80"
