# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Define environment variable
ENV REACT_APP_API_URL=http://api:80

# Run the app
CMD ["npm", "start"]

# Optional: Add metadata (author label)
LABEL authors="flavi"
